config/routes.rb
Rails.application.routes.draw do
  resources :point_types
  resources :locations
  resources :trips
  resources :routes
  resources :points

  root 'pages#index'

end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :location
  belongs_to :point_type
  belongs_to :trip

#  acts_as_list scope: :trip

  validates :location_id, presence: true, uniqueness: true
  validates :point_type_id, presence: true
  validates :trip_id, presence: true

  def coords
    "#{self.location.coords}"
  end

  def type
    "#{self.point_type.name}"
  end
end

app/models/point_type.rb
class PointType < ActiveRecord::Base
  has_one :point

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:location_id, :point_type_id, :trip_id, :position, :hidden_from_map, :hidden_from_map)
    end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :point_type_id %><br>
    <%= f.text_field :point_type_id %>
  </div>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>

  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.text_field :trip_id %>
  </div>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.check_box :hidden_from_map %>
    <%= f.label :hidden_from_map %>
  </div>

  <div class="field">
    <%= f.check_box :hidden_from_list %>
    <%= f.label :hidden_from_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing Point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Points</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Coords</th>
      <th>Linha</th>
      <th>Ordem</th>
      <th>Visível na lista</th>
      <th>Visível no mapa</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.point_type_id %></td>
        <td><%= point.coords %></td>
        <td><%= point.trip.headsign %></td>
        <td><%= point.position %></td>
        <td><%= point.hidden_from_list %></td>
        <td><%= point.hidden_from_map %></td>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New Point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>