config/routes.rb
Rails.application.routes.draw do
  resources :point_types
  resources :locations
  resources :trips
  resources :routes
  resources :points

  root 'pages#index'

end

app/controllers/point_types_controller.rb
class PointTypesController < ApplicationController
  before_action :set_point_type, only: [:show, :edit, :update, :destroy]

  # GET /point_types
  # GET /point_types.json
  def index
    @point_types = PointType.all
  end

  # GET /point_types/1
  # GET /point_types/1.json
  def show
  end

  # GET /point_types/new
  def new
    @point_type = PointType.new
  end

  # GET /point_types/1/edit
  def edit
  end

  # POST /point_types
  # POST /point_types.json
  def create
    @point_type = PointType.new(point_type_params)

    respond_to do |format|
      if @point_type.save
        format.html { redirect_to @point_type, notice: 'Point type was successfully created.' }
        format.json { render :show, status: :created, location: @point_type }
      else
        format.html { render :new }
        format.json { render json: @point_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_types/1
  # PATCH/PUT /point_types/1.json
  def update
    respond_to do |format|
      if @point_type.update(point_type_params)
        format.html { redirect_to @point_type, notice: 'Point type was successfully updated.' }
        format.json { render :show, status: :ok, location: @point_type }
      else
        format.html { render :edit }
        format.json { render json: @point_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_types/1
  # DELETE /point_types/1.json
  def destroy
    @point_type.destroy
    respond_to do |format|
      format.html { redirect_to point_types_url, notice: 'Point type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_type
      @point_type = PointType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_type_params
      params[:point_type]
    end
end

app/helpers/point_types_helper.rb
module PointTypesHelper
end

app/views/point_types/_form.html.erb
<%= form_for(@point_type) do |f| %>
  <% if @point_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point_type.errors.count, "error") %> prohibited this point_type from being saved:</h2>

      <ul>
      <% @point_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/point_types/edit.html.erb
<h1>Editing Point Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @point_type %> |
<%= link_to 'Back', point_types_path %>

app/views/point_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Point Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @point_types.each do |point_type| %>
      <tr>
        <td><%= link_to 'Show', point_type %></td>
        <td><%= link_to 'Edit', edit_point_type_path(point_type) %></td>
        <td><%= link_to 'Destroy', point_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point type', new_point_type_path %>

app/views/point_types/new.html.erb
<h1>New Point Type</h1>

<%= render 'form' %>

<%= link_to 'Back', point_types_path %>

app/views/point_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_point_type_path(@point_type) %> |
<%= link_to 'Back', point_types_path %>