config/routes.rb
Rails.application.routes.draw do
  resources :point_types
  resources :locations
  resources :trips
  resources :routes
  resources :points

  root 'pages#index'

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :trips, :inverse_of => :route, :dependent => :destroy

  validates :number, presence: true, uniqueness: true, format: { with: /\A[0-9]{3,4}\-?\w?\z/ }
  validates :name, presence: true, uniqueness: true, length: { in: 3..50 }, format: { with: /\A.+\s\/\s.+\z/ }

  def full_name
    "#{number} - #{name}"
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:number, :name, :circulator)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.slim
= form_for(@route) do |f|

  = render partial: 'errors/list', locals: { form: @route }

  .field
    = f.label :number
    br
    = f.text_field :number

  .field
    = f.label :name
    br
    = f.text_field :name

  .field
    = f.check_box :circulator
    = f.label :circulator

  .actions
    = f.submit

app/views/routes/edit.slim
h1 Editing Route

= render 'form'

= link_to 'Show', @route
|  |
= link_to 'Back', routes_path

app/views/routes/index.slim
h1 Listing Routes

table
  tr
    th Number
    th Name
    th Circular
    th colspan="3"
  - @routes.each do |route|
    tr
      td = route.number
      td = route.name
      td = route.circulator
      td = link_to 'Show', route
      td = link_to 'Edit', edit_route_path(route)
      td = link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' }

br

= link_to 'New Route', new_route_path

app/views/routes/new.slim
h1 New Route

= render 'form'

= link_to 'Back', routes_path

app/views/routes/show.slim
p
  strong Number: 
  = @route.number

p
  strong Name: 
  = @route.name

p
  strong Circular: 
  = @route.circulator

= link_to 'Edit', edit_route_path(@route)
|  |
= link_to 'Back', routes_path